---
# Main docker-compose file for PiHome

name: pihome

include:
  - ../utils/docker-compose.yml
  - ./Security/docker-compose.yml
  - ./pihole-docker-compose.yml
  - ./IOT/docker-compose.yml
  - ./Apps/docker-compose.yml
  # Uncomment the following line to include Finances services
  # - ./Finances/docker-compose.yml

services:
  nginx:
    container_name: nginx
    image: nginx:1.29-alpine
    volumes:
      - type: bind
        source: /home/pi/config/nginx/etc/nginx/templates
        target: /etc/nginx/templates
      - type: bind
        source: /home/pi/Home-Lab-Containers/PiHome/nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=192.168.0.68
      - NGINX_PORT=80
    restart: unless-stopped
