---
# Main docker-compose file for PiHome

name: pihome

include:
  - path: ../utils/docker-compose.yml
    env_file: ./Networking/.env
  - ./Security/docker-compose.yml
  - ./Networking/docker-compose.yml
  - ./IOT/docker-compose.yml
  - ./Apps/docker-compose.yml
  # Uncomment the following line to include Finances services
  # - ./Finances/docker-compose.yml
