---
name: security

services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable
    restart: unless-stopped
    privileged: true
    shm_size: "512mb"

    ports:
      - "0.0.0.0:8971:8971"
      - "0.0.0.0:5000:5000"
      - "0.0.0.0:8554:8554"
      - "0.0.0.0:8555:8555/tcp"
      - "0.0.0.0:8555:8555/udp"

    volumes:
      - type: bind
        source: /home/pi/docker-mounts/frigate/config
        target: /config
      - type: bind
        source: /home/pi/docker-mounts/frigate/media
        target: /media/frigate
      - /etc/localtime:/etc/localtime:ro
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000