---

version: "3.7"

services:
  motion-eye:
    image: ccrisan/motioneye:master-armhf
    container_name: Motion-Eye
    environment:
      - TZ=Europe/London
    volumes:
      - type: bind
        source: /home/pi/docker-mounts/etc
        target: /etc
      - type: bind
        source: /home/pi/docker-mounts/var
        target: /var
    ports:
      - 8765:8765
    restart: unless-stopped
