---
# Main docker-compose file for HPNas

name: hpnas

include:
  - ../utils/docker-compose.yml
  - path: ../utils/Networking/docker-compose.yml
    env_file: ./Networking/.env
  - ./Storage/docker-compose.yml
  - ./Misc/docker-compose.yml
