---
name: storage

services:
  Gitlab:
    image: gitlab/gitlab-ce:19.2.1-ce.0
    container_name: GitLab
    volumes:
      - /mnt/USB3.0-1TB/GitLab/config:/etc/gitlab
      - /mnt/USB3.0-1TB/GitLab/logs:/var/log/gitlab
      - /mnt/USB3.0-1TB/GitLab/data:/var/opt/gitlab
    ports:
      - '0.0.0.0:1022:22'
      - '0.0.0.0:1080:80'
      - '0.0.0.0:1443:1443'
    restart: unless-stopped
    stdin_open: true
    tty: true

  samba:
    image: dockurr/samba:4.23.10
    container_name: samba
    environment:
      USER: "${SAMBA_USER}"
      PASS: "${SAMBA_PASSWORD}"
      NAME: "Storage"
      RW: "true" # Enables read-write access for authenticated users
      UID: 1000
      GID: 1000
    volumes:
      # Mount each volume to its matching /storageX path
      - /mnt/USB3.0-1TB/Storage:/Storage/Storage
      - /mnt/USB3.0-1TB/Courses:/Storage/Courses
      - /mnt/MediaStorage/Books:/Storage/Books
      - /mnt/MediaStorage/AudioBooks:/Storage/AudioBooks
    network_mode: host
    restart: unless-stopped
