---
name: storage

services:
  Gitlab:
    image: gitlab/gitlab-ce:18.10.0-ce.0
    container_name: GitLab
    volumes:
      - /mnt/USB3.0-1TB/GitLab/config:/etc/gitlab
      - /mnt/USB3.0-1TB/GitLab/logs:/var/log/gitlab
      - /mnt/USB3.0-1TB/GitLab/data:/var/opt/gitlab
    ports:
      - '0.0.0.0:1022:22'
      - '0.0.0.0:1080:80'
      - '0.0.0.0:1443:1443'
    restart: unless-stopped
    stdin_open: true
    tty: true
  samba:
    image: dperson/samba:amd64
    container_name: samba
    volumes:
      - /mnt/USB3.0-1TB/Storage:/Storage
      - /mnt/USB3.0-1TB/Courses:/Courses
      - /home/pi/config/samba:/etc/samba
      - /mnt/MediaStorage/Books:/Books
      - /mnt/MediaStorage/AudioBooks:/AudioBooks
    environment:
      - PUID:1000
      - PGID:1000
    network_mode: host
    command: '-u "USERNAMEGOESHERE;PASSWORDGOESHERE"'
    restart: unless-stopped
    stdin_open: true
    tty: true
