---

version: '3.7'

services:

  Portainer:
    image: portainer/portainer-ce
    container_name: portainer
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - portainer_data:/data
    ports:
      - 8000:8000
      - 9443:9443
      - 9000:9000
    restart: unless-stopped

  Agent:
    image: portainer/agent
    container_name: portainer_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - 9001:9001
    restart: unless-stopped

  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    ports:
      - 3001:3001
    volumes:
      - type: bind
        source: /home/pi/config/uptime-kuma
        target: /app/data
    restart: unless-stopped

volumes:
  portainer_data:
