version: '3.7'

services:
  
  Portainer:
    image: portainer/portainer-ce
    container_name: portainer
    volumes:
     - type: bind
       source: /var/run/docker.sock
       target: /var/run/docker.sock
     - portainer_data:/data
    ports:
      - 8000:8000
      - 9443:9443
      - 9000:9000
    restart: unless-stopped

  Agent:
    image: portainer/agent
    container_name: portainer_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - 9001:9001
    restart: unless-stopped

  wifi-connect:
        build: ./wifi-connect
        container_name: wifi_Connect
        network_mode: "host"
        labels:
            io.balena.features.dbus: '1'
        cap_add:
            - NET_ADMIN
        environment:
            DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"

volumes:
  portainer_data: