services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
    - type: bind
      source: /home/pi/config/nginx/etc/nginx/templates
      target: /etc/nginx/templates
    - type: bind
      source: /home/pi/config/nginx/etc/nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    ports:
    - "80:80"
    environment:
    - NGINX_HOST=192.168.0.43
    - NGINX_PORT=80