---

name: Static Analysis
on: [push]

jobs:
  Shell_Check:
    name: Shell Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: sudo apt-get install -y shellcheck
      - name: Shell Check
        run: |
            echo "Checking shell scripts"
            find . -type f -name "*.sh" -print0 | xargs -0 shellcheck

  Markdown_Lint_Check:
    name: Markdown Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run markdownlint
        run: |
          echo "Checking Markdown files"
          find . -type f -name "*.md" -print0 | xargs -0 markdownlint
  Dockerfile_Lint_Check:
    name: Dockerfile Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Download Packages
        run: |
          sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.10.0/hadolint-Linux-x86_64
          sudo chmod +x /bin/hadolint .
      - name: Dockerfile Lint
        run: |
          hadolint --failure-threshold error --verbose *Dockerfile
      - name: Docker Compose Lint
        run: |
          docker-compose config  || { echo "Invalid Docker Compose file"; exit 1; }
          
  YAML_Lint_Check:
    name: YAML Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Install yamllint
        run: sudo apt install yamllint
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run yamllint
        run: |
          echo "Checking YAML files"
          find . -type f -name "*.yml" -print0 | xargs -0 yamllint
          find . -type f -name "*.yaml" -print0 | xargs -0 yamllint
