version: "3"

services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/pi/config/heimdall/config:/config
    ports:
      - 8000:80
      - 443:443
    restart: unless-stopped