---
# Main docker-compose file for PiDesk
# This file includes all services for the PiDesk system using Docker Compose's include feature

name: printing

include:
  - ../utils/docker-compose.yml
  - ./Networking/docker-compose.yml
  - ./docker-compose.local.yml
